name: "⛴️  Fetch Github Repositories"

on:
  workflow_dispatch:
    inputs:
      language:
        description: 'Filter repositories by coding language'
        required: true
        default: 'python'
      limit:
        description: 'Maximum number of repositories to fetch'
        required: true
        default: '100'
      stars:
        description: 'Filter on number of stars'
        required: true
        default: '500'

jobs:
  fetch-repos:
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v4
        with:
          ref: 'gh-actions'

      - name: Fetch Repositories
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          gh search repos --stars ">${{ github.event.inputs.stars }}" --language=${{ github.event.inputs.language }} --jq ".[].url" --json "url" --limit=${{ github.event.inputs.limit }} > queue_files/$(date +%s).txt

      - name: Git Auto Commit
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          # Optional. Local and remote branch name where commit is going to be pushed
          #  to. Defaults to the current branch.
          #  You might need to set `create_branch: true` if the branch does not exist.
          branch: gh-actions

          # Optional. Create given branch name in local and remote repository.
          create_branch: true

          # Optional. Commit message for the created commit.
          # Defaults to "Apply automatic changes"
          commit_message: Fetch Repository List into the queue_files directory

